captcha/urls.py
from django.urls import path

from captcha import views

app_name = 'captcha'
urlpatterns = [
    path('check/', views.CaptchaCheck.as_view(), name='captcha_check'),
]

file_editor/urls.py
from django.urls import path

from file_editor import views

app_name = 'files'
urlpatterns = [
    path('', views.FileCreate.as_view(), name='home'),
    path('files/<int:pk>/update/', views.FileUpdate.as_view(), name='update'),
    path('files/<int:pk>/', views.FileDetail.as_view(), name='detail'),
    path('files/', views.FileList.as_view(), name='list'),
]

lab1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_editor.urls')),
    path('users/', include('users.urls')),
    path('captcha/', include('captcha.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('activate/', views.Activate.as_view(), name='activate'),
]

captcha/models.py
from django.db import models


# Create your models here.
class Captcha(models.Model):
    subject = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)


class CaptchaImage(models.Model):
    cap = models.ForeignKey(Captcha, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField()
    correct_answer = models.BooleanField(default=False)

file_editor/models.py
import os
from datetime import datetime

from django.db import models


# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe


class HtmlFile(models.Model):
    file = models.FileField(upload_to='files/')

    @property
    def content(self):
        with open(self.file.path, 'r') as f:
            return mark_safe(f.read())

    @property
    def info(self):
        foo = os.path.getmtime(self.file.path)
        def convert_date(date):
            return datetime.fromtimestamp(date).strftime('%Y-%m-%d %H:%M:%S')
        return mark_safe(f"""
            <b>Size:</b> {os.path.getsize(self.file.path)}<br/>
            <b>Last Modified:</b> {convert_date(os.path.getmtime(self.file.path))}<br/>
            <b>Created:</b> {convert_date(os.path.getctime(self.file.path))}<br/>
        """)

    def get_absolute_url(self):
        return reverse('files:update', args=(self.pk,))

users/models.py
from django.db import models


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(SingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()


# Create your models here.
class IsActivated(SingletonModel):
    is_activated = models.BooleanField(default=False)

captcha/forms.py
from django import forms

from captcha.models import Captcha, CaptchaImage


class CaptchaForm(forms.Form):
    def clean(self):
        cleaned_data = super().clean()
        images = cleaned_data['images']
        captcha = cleaned_data['captcha']

        correct_images = captcha.images.filter(correct_answer=True)
        if list(images.all()) != list(correct_images.all()):
            raise forms.ValidationError('Incorrect answer')
        return cleaned_data

    images = forms.ModelMultipleChoiceField(queryset=CaptchaImage.objects.all())
    captcha = forms.ModelChoiceField(queryset=Captcha.objects.all())

file_editor/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.core.files.base import ContentFile

from file_editor.models import HtmlFile


class EditorForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.id:
            self.fields['content'].initial = self.instance.content

    def save(self, commit=True):
        instance = super().save(commit=False)
        if instance.file:
            with open(instance.file.path, 'w') as f:
                f.write(self.cleaned_data['content'])
        else:
            instance.file.save('filename.html', ContentFile(self.cleaned_data['content']))
        if commit:
            instance.save()
        return instance

    class Meta:
        model = HtmlFile
        fields = ('content',)

users/forms.py
from django import forms


class ActivateForm(forms.Form):
    code = forms.CharField(max_length=255, help_text='Enter activation code')

captcha/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

from captcha.forms import CaptchaForm
from captcha.models import Captcha


class CaptchaCheck(View):
    def get(self, request, *args, **kwargs):
        form = CaptchaForm(request.POST)
        # get random captcha
        captcha = Captcha.objects.order_by('?').first()
        form.instance = captcha
        images = captcha.images.order_by('?').all()
        return render(request, 'captcha/captcha_check.html', {'form': form, 'captcha': captcha, 'cap_images': images})

    def post(self, request, *args, **kwargs):
        form = CaptchaForm(request.POST)
        if form.is_valid():
            return render(request, 'captcha/captcha_success.html')
        return render(request, 'captcha/captcha_failed.html')

file_editor/views.py
# Create your views here.
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from file_editor.forms import EditorForm
from file_editor.models import HtmlFile


class FileCreate(CreateView):
    form_class = EditorForm
    template_name = 'file_editor/home.html'


class FileDetail(DetailView):
    queryset = HtmlFile.objects.all()
    template_name = 'file_editor/file_detail.html'


class FileUpdate(UpdateView):
    form_class = EditorForm
    queryset = HtmlFile.objects.all()
    template_name = 'file_editor/file_edit.html'


class FileList(ListView):
    queryset = HtmlFile.objects.all()
    template_name = 'file_editor/html_file_list.html'

    def get_queryset(self):
        query = self.request.GET.get('filename', '')
        return HtmlFile.objects.filter(file__icontains=query)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

from users.forms import ActivateForm
from users.models import IsActivated

ALPHABET = ' abcdefghijklmnopqrstuvwxyz'


def vigenere_cipher(text, key):
    # vigenere cipher with whitespace
    cipher = ''
    for i, c in enumerate(text):
        if c.isalpha() or c.isspace():
            idx = ALPHABET.index(c.lower())
            letter = ALPHABET[(idx + ALPHABET.index(key[i % len(key)])) % len(ALPHABET)]
            cipher += letter.upper() if c.isupper() else letter
        else:
            cipher += c
    return cipher


KEYWORD = 'iron'
ACTIVATION_CODE = 'Iron is a vital trace element for humans'
ENCRYPTED_CODE = vigenere_cipher(ACTIVATION_CODE, KEYWORD)


class Activate(View):
    def get(self, request, *args, **kwargs):
        form = ActivateForm()
        return render(request, 'users/activate.html', {'form': form})

    def post(self, request, *args, **kwargs):
        f = ActivateForm(request.POST)
        if f.is_valid():
            code = f.cleaned_data['code']
            if vigenere_cipher(code, KEYWORD) == ENCRYPTED_CODE:
                IsActivated.objects.update_or_create(is_activated=True)
                return render(request, 'users/activate_success.html')
            f.add_error('code', 'Invalid activation code')

        return render(request, 'users/activate.html', {'form': f})

captcha/templates/captcha/captcha_check.html
{% extends 'file_editor/base.html' %}

{% block title %}Captcha Check{% endblock %}

{% block head_additional %}
    <style>
        .captcha_image_input {
            display: none;
        }

        .img_item.selected {
            outline: 7px solid aquamarine;
            transform: scale(.9);
        }

        .images_box {
            max-width: 300px;
        {#margin: 0 auto;#} display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-auto-rows: 1fr;
            grid-column-gap: 10px;
            grid-row-gap: 10px;
        }

        .img_item {
            background-size: cover;
            width: 100px;
            height: 120px;
        {#overflow: hidden;#}
        }

        .captcha-image {
            width: auto;
            height: 100%;
            border: 1px solid #ccc;
            cursor: pointer;
        }

        .main_container {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-top: 9em;
        }

        .captcha_title {
            margin-bottom: .8em;
        }

        .captcha-btn {
            margin: .8em auto;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" class="main_form" method="post">
        {% csrf_token %}
        <input type="hidden" name="captcha" value="{{ captcha.pk }}">
        <h4 class="captcha_title">Select images with {{ captcha.subject }}</h4>
        <div class="images_box">
            {% for im in cap_images %}
                <div class="img_item" style="background-image: url('{{ im.image.url }}')"
                     data-image_id="image{{ im.pk }}">
                    <input type="checkbox" name="images" id="image{{ im.pk }}" value="{{ im.pk }}"
                           class="captcha_image_input">
                </div>
            {% endfor %}
        </div>
        <button class="btn btn-primary captcha-btn">
            <span class="glyphicon glyphicon-ok"></span>
            Submit
        </button>
    </form>
{% endblock %}

{% block js %}
    <script>
        document.querySelectorAll('.img_item').forEach(function (el) {
            el.addEventListener('click', function (e) {
                e.preventDefault();
                var input = document.querySelector('#' + e.target.dataset.image_id);
                input.checked = !input.checked;
                e.target.classList.toggle('selected');
            });
        });
    </script>
{% endblock %}

captcha/templates/captcha/captcha_failed.html
{% extends 'file_editor/base.html' %}

{% block content %}You are robot{% endblock %}

captcha/templates/captcha/captcha_success.html
{% extends 'file_editor/base.html' %}

{% block content %}You are <b>not</b> robot{% endblock %}

file_editor/templates/file_editor/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/ba019e07df.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block head_additional %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<main class="container">
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-light sidebar" style="width: 280px;">
        <a href="{% url 'files:home' %}"
           class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap"></use>
            </svg>
            <span class="fs-4">Hello</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="{% url 'files:home' %}" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16">
                        <use xlink:href="#home"></use>
                    </svg>
                    Create file
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'files:list' %}" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16">
                        <use xlink:href="#home"></use>
                    </svg>
                    All files
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:activate' %}" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16">
                        <use xlink:href="#speedometer2"></use>
                    </svg>
                    Activate product
                </a>
            </li>
            <hr>
            <li class="nav-item">
                <a href="{% url 'captcha:captcha_check' %}" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16">
                        <use xlink:href="#speedometer2"></use>
                    </svg>
                    Turing test
                </a>
            </li>

        </ul>
        <hr>
    </div>
    <div class="main_content">
        {% block content %}{% endblock %}
    </div>
</main>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        let nav_links = document.querySelectorAll('.nav-link');
        for (nl of nav_links) {
            if (nl.href === window.location.href) {
                nl.classList.add('active');
                nl.classList.remove('link-dark');
            }
        }
    })
</script>
{% block js %}{% endblock %}
</body>
</html>

file_editor/templates/file_editor/file_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ object.content|safe }}
</body>
</html>

file_editor/templates/file_editor/file_edit.html
{% extends 'file_editor/base.html' %}
{% load static %}
{% block head_additional %}
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/file_edit.css' %}">
{% endblock %}
{% block title %}File{% endblock %}

{% block content %}
    <div class="container__inner">
        <input type="file" id="file-input"/>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" id="save-file_btn" type="submit">Save file</button>
        </form>
    </div>

    {% if request.activated %}
        <div class="premium-buttons mt-5">
            <button class="btn btn-info" onclick="printFile()">Print file</button>
        </div>
    {% endif %}
{% endblock content %}]

{% block js %}
    <script>
        {#window.alert('Buy our soft');#}

        function readSingleFile(e) {
            var file = e.target.files[0];
            let imageUrl = URL.createObjectURL(file);
            console.log(imageUrl);
            if (!file) {
                return;
            }
            var reader = new FileReader();
            reader.onload = function (e) {
                var contents = e.target.result;
                displayContents(contents);
            };
            reader.readAsText(file);

        }

        function displayContents(contents) {
            CKEDITOR.instances.id_content.setData(contents);
        }

        document.getElementById('file-input')
            .addEventListener('change', readSingleFile, false);

        function printFile() {
            var printContents = CKEDITOR.instances.id_content.getData();
            var mywindow = window.open('', 'PRINT',);
            mywindow.document.write(printContents);
            mywindow.document.close(); // necessary for IE >= 10
            mywindow.focus(); // necessary for IE >= 10*/

            mywindow.print();
            mywindow.close()
        }

    </script>
{% endblock js %}

file_editor/templates/file_editor/home.html
{% extends 'file_editor/base.html' %}
{% block head_additional %}
    {{ form.media }}
{% endblock %}
{% block title %}File{% endblock %}

{% block content %}
    <div class="container__inner">
        <input type="file" id="file-input"/>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" id="save-file_btn" type="submit">Save file</button>
        </form>
    </div>
{% endblock content %}]

{% block js %}
    <script>
        {#window.alert('Buy our soft');#}

        function readSingleFile(e) {
            var file = e.target.files[0];
            let imageUrl = URL.createObjectURL(file);
            console.log(imageUrl);
            if (!file) {
                return;
            }
            var reader = new FileReader();
            reader.onload = function (e) {
                var contents = e.target.result;
                displayContents(contents);
            };
            reader.readAsText(file);

        }

        function displayContents(contents) {
            CKEDITOR.instances.id_content.setData(contents);
        }

        document.getElementById('file-input')
            .addEventListener('change', readSingleFile, false);

        document.getElementById('save-file_btn')
            .addEventListener('click', () => {
                // save file to the disk

            })

    </script>
{% endblock js %}

file_editor/templates/file_editor/html_file_list.html
{% extends 'file_editor/base.html' %}
{% load static %}

{% block head_additional %}
    <link rel="stylesheet" href="{% static 'css/file_list.css' %}">
{% endblock %}

{% block content %}
    {% if request.activated %}
        <form method="get" class="input-group file_search">
            <input type="search" class="form-control rounded" placeholder="Search by name" aria-label="Search"
                   aria-describedby="search-addon" name="filename"/>
            <button type="button" class="btn btn-outline-primary">search</button>
        </form>
    {% endif %}
    <table class="table file_list">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">URL</th>
            <th scope="col">Content</th>
            <th scope="col">Info</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <th scope="row">{{ item.pk }}</th>
                <td><a href="{{ item.file.url }}">{{ item.file }}</a></td>
                <td>{{ item.content | safe | truncatechars_html:50 }}</td>
                <td>{{ item.info }}</td>
                <td><a href="{% url 'files:update' item.pk %}"><i class="fa fa-edit"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

users/templates/users/activate.html
{% extends 'file_editor/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Activate product{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}

users/templates/users/activate_success.html
{% extends 'file_editor/base.html' %}

{% block title %}Activation successful{% endblock %}

{% block content %}Congratulations, now you have activated product.{% endblock %}